### ISSUE TITLE
Change all instances of ember-table-jsonapi to ember-tabular for consistency

### ISSUE THREAD

**Issue by Aaronfischer** [caxiam/ember-tabular#30]

**Comment by Aaronfischer** [comment]
@morgan I've pondered over what to rename `bindModel`, thats a bit more clear...
The model can be generated by the component OR the model can be generated by the route and passed in.

Any ideas?

**Comment by morgan** [comment]
@Aaronfischer `record` :-)

For `modelType`, what do you think about changing it to `modelName`? Looking at Ember-Data documentation, it would then following conventions: http://emberjs.com/api/data/classes/DS.Store.html#method_findRecord

**Comment by Aaronfischer** [comment]
Yes, agreed! You know I thought I referenced the API in that convention (modelType). Apparently not. 

I'll make this change very shortly, then I'll start queue up open projects in fresh PR.
