### ISSUE TITLE
Infinite loop of requests when using global date picker

### ISSUE THREAD

**Issue by Aaronfischer** [caxiam/ember-tabular#58]

**Comment by Aaronfischer** [comment]
@morgan Very strange bug I've discovered... so the issue is that when the global date picker is used (user selects date) it creates an infinite loop of requests due to `filter.@each.value`. (or `filter`) being triggered which fires the `query()` method, request is made, etc, etc.

Another strange thing is while debugging this I created a number of observers to try and pinpoint the problem.
```js
  ...
  testFilter: Ember.observer('filter', function() {
    console.log('filter');
  }),
  ...
```
Even adding just this observer creates the infinite loop (without any user interaction with the global date), in fact it creates an infinite loop of requests on my other example that uses a global text input... No user interaction, just directly on load it creates an infinite loop of GET requests.

I'll continue to debug in the morning but didn't know if you had any ideas off the top of your head?
(why would adding an observer trigger the computed property to infinitely run? So is this a large issue with how I'm sharing properties between parent/child components?)

**Comment by morgan** [comment]
@Aaronfischer Couple thoughts:

1. Start off by adding a failing test. Let's replicate the behavior so we can check for it once resolved.
2. Then start tracing through the nesting. Observe the behavior across other properties. Try and narrow down the scope of the issue. From a debugging standpoint, it's a matter of reducing the amount of moving pieces. Try and isolate the root cause. I'm happy to dive in if needed.

**Comment by Aaronfischer** [comment]
@morgan So I think I've determined that the bug occurs when `ember-tabular-dropdown-filter` is paired with `ember-tabular-date-filter`. Although if `ember-tabular-dropdown-filter` is used before `ember-tabular-date-filter` then the bug does not occur.

And... `ember-tabular-date-filter` does not trigger the bug by itself.

------

After further debugging, if you strip it all the way down to just a basic implementation of ember-tabular without any global filters, but you expose `filter=filter2` on `{{#ember-tabular` and you add an extra observer in to the ember-tabular.js source you will get an infinite loop:
```hbs
// tests/dummy/app/templates/index.hbs
{{#ember-tabular class="table-basic-global-date-filter" columns=columns2 modelName="user" record=users2 filter=filter2 as |section|}}
    {{#if section.isHeader}}
        ...
    {{else if section.isBody}}
        {{#each users2 as |row|}}
            <tr>
                <td>{{row.username}}</td>
                <td>{{row.emailAddress}}</td>
                <td>{{row.firstName}}</td>
                <td>{{row.lastName}}</td>
                <td>
                    {{#if row.updatedAt}}
                        {{moment-format row.updatedAt 'MM/DD/YYYY'}}
                    {{else}}
                        {{moment-format row.createdAt 'MM/DD/YYYY'}}
                    {{/if}}
                </td>
            </tr>
        {{/each}}
    {{/if}}
{{/ember-tabular}}
```
```js
// addon/components/ember-tabular.js
  testFilter: Ember.observer('filter.@each.value', function() {
    console.log('testFilter', this.get('filter'));
  }),
```
... however this is solved by ensuring that the filter, that is exposed on the controller (`filter2`) is set to `null`, this prevents the infinite loop, I guess because `undefined` does not play well with observers?

--------

Then, as a final test... I used the original example `ember-tabular-dropdown-filter` and `ember-tabular-date-filter`, and began removing pieces that were shared with the controller, thinking that this `undefined` may be the culprit... `isAdminFilter` is a controller property that was not originally defined on the controller (same as `filterX`).
Once this is defined, and set to `null`... I am unable to replicate the infinite request loop. 
It seems to be solved.

So it appears that any property shared with ember-tabular or any of it sub-components requires that the property be defined. (In this case, on the controller)

When you get a chance to look over this issue, could you test a few of my findings and see if you can replicate this solution as well as break it? 😄

**Comment by Aaronfischer** [comment]
@morgan A few more important focuses for the bulk of tomorrow but when I get a chance to circle back around, I'll attempt to write a failing test around this... (not sure why they didn't work before), as well as clean up something I noticed within the sub-components (opportunity to stay DRY).

**Comment by morgan** [comment]
@Aaronfischer You seem to be on a good path here. Try and push through. If you find yourself throwing in the towel, I'm happy to jump in and provide another set of eyes.
