### ISSUE TITLE
Reloading the table?

### ISSUE THREAD

**Issue by mbarringer** [caxiam/ember-tabular#75]
My apologies if this is a dumb question - when I create or remove a record in the datastore, the new records aren't visible in the ember-tabular table until a page refresh. Modifying existing field data is reflected immediately, just not newly created records.

What is the recommended way to update the table with the latest information in the datastore?

**Comment by Aaronfischer** [comment]
Hey @mbarringer,
How are you populating ember-tabular? Are you making the request on the route and passing that through the controller into ember-tabular? Or are you having ember-tabular make the request for you?

You can accomplish it either way. We typically have tabular make the request. So when a route is transitioned into and tabular is initialized it will fire a request to the server to get the most up to date data.

**Comment by mbarringer** [comment]
I have tabular handling everything, and it works wonderfully except when data is changed locally, either by creating and saving a record, or by deleting it. The datastore itself reflects the change, and the change is successfully sent to the server, but the HTML table only contains the data in the state it was when it was initially loaded. So I'm looking for the right way to either have tabular automatically update the HTML based on the updated datastore, or to tell it to reload from the server in the background. 

Looking at the code, I didn't see any obvious way to do either of those things, but I don't have a huge amount of ember experience, so I assume I'm doing something wrong: when I remove a record, I call `deleteRecord()` and `save()` from the controller, without any other route transition. When adding a record, the user is bounced to a subroute containing a modal dialog, and then after saving the record, the subroute calls `transitionTo()` back to the route with the tabular component, which then doesn't show the new record until the entire page is reloaded.

(This is with Ember 2.7 and ember-tabular directly from git as of December 2nd)

**Comment by Aaronfischer** [comment]
@mbarringer When the user is bounced back to the route with the tabular component (from the subroute) is tabular firing a request to the server?

**Comment by mbarringer** [comment]
I think I see what's wrong: we actually have two ember-tabular tables on the same page, both with different query parameters, different data sets, and different record parameters specified in the controller, but ultimately using the same ember data model. I don't know why I didn't stop to think that there's no way for tabular to know which table to assign a new record to in the first place.

I've gotten it so that removing records in the data store are now immediately removed from the table (although the pager doesn't seem to be updated), and I've worked around the lack of a refresh upon transitioning back by explicitly calling recordParameter.update() in the controller after the route has transitioned. It's maybe not the best way to do it, but it's smooth and doesn't duplicate network calls, so I'm happy with that.

Sorry for the noise! The problem was most definitely my fault, so I'll close this.

**Comment by Aaronfischer** [comment]
@mbarringer Sure thing, let me know if you have any other questions!
